services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8282:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:pick_a_password@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pick_another_password
      - POLLING_FREQUENCY = 1
      - SCHEDULER_ROUND_ROBIN_MIN_INTERVAL = 20
      - BATCH_SIZE = 5
    restart: unless-stopped
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=pick_a_password
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped
volumes:
  miniflux-db:
